version: '2.1'
services:
    redis:
        image: 'redis:5.0.5'
        # command: redis-server --requirepass redispass

    postgres:
        image: postgres:13
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        # Uncomment these lines to persist data on the local filesystem.
        #     - PGDATA=/var/lib/postgresql/data/pgdata
        # volumes:
        #     - ./pgdata:/var/lib/postgresql/data/pgdata

    airflow-dbinit:
        image: ctakes-mr-edge:latest
        container_name: airflow-dbinit
        depends_on:
            - postgres
        command: db init
        

    airflow-dbuser:
        image: ctakes-mr-edge:latest
        container_name: airflow-dbuser
        depends_on:
            - airflow-dbinit
        command: users create -r Admin -u admin -e admin@example.com -f admin -l user -p test

    webserver:
        image: ctakes-mr-edge:latest
        restart: "always"
        depends_on:
            - redis
            - airflow-dbuser
        environment:
            - LOAD_EX=n
            - EXECUTOR=Celery
            - AIRFLOW__CORE__FERNET_KEY=Mdko2auzd9rHBf_HEvxm2C1Lq2yS196GgwpmdWYn_-A=
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        volumes:
            - ./dags:/opt/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/opt/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver

        healthcheck:
            test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: ctakes-mr-edge:latest
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            # - REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: celery flower

    scheduler:
        image: ctakes-mr-edge:latest
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/opt/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/opt/airflow//plugins
        environment:
            - LOAD_EX=n
            - EXECUTOR=Celery
            - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
            - AIRFLOW__CORE__FERNET_KEY=Mdko2auzd9rHBf_HEvxm2C1Lq2yS196GgwpmdWYn_-A=
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: scheduler

    worker:
        image: ctakes-mr-edge:latest
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/opt/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/opt/airflow/plugins
        environment:
            - EXECUTOR=Celery
            - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
            - AIRFLOW__CORE__FERNET_KEY=Mdko2auzd9rHBf_HEvxm2C1Lq2yS196GgwpmdWYn_-A=
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: celery worker
